version: "3"
services:

  {{model_id}}_cpu:
    image: {{repository_name}}:1
    volumes:
      - "${INPUT_DATA}:/var/data/input"
      - "${OUTPUT_DATA}:/var/data/output"
    environment:
      - INPUT_DATA=/var/data/input
      - OUTPUT_DATA=/var/data/output


