version: "3"
services:

  model_ecaas_agrifieldnet_silver_v1_cpu:
    image: model_ecaas_agrifieldnet_silver:1
    volumes:
      - "${INPUT_DATA}:/var/data/input"
      - "${OUTPUT_DATA}:/var/data/output"
    environment:
      - INPUT_DATA=/var/data/input
      - OUTPUT_DATA=/var/data/output


